# Generated by Django 5.1.3 on 2024-12-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginpage', '0002_alter_member_birthday_alter_member_nicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=1000)),
                ('bcontent', models.TextField()),
                ('bdate', models.DateTimeField(auto_now=True)),
                ('bfile', models.ImageField(null=True, upload_to='')),
                ('like_members', models.ManyToManyField(default='', related_name='like_member', to='loginpage.member')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginpage.member')),
            ],
        ),
    ]
