# Generated by Django 5.1.3 on 2024-12-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='member',
            field=models.CharField(default='관리자', max_length=100),
        ),
    ]
