# Generated by Django 5.1.3 on 2024-12-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_noticeboard_member'),
        ('loginpage', '0002_alter_member_birthday_alter_member_nicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='bfile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='like_members',
            field=models.ManyToManyField(blank=True, related_name='like_member', to='loginpage.member'),
        ),
    ]
