# Generated by Django 5.1.3 on 2024-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_noticeboard_like_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='bfile_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='category',
            field=models.IntegerField(null=True),
        ),
    ]
