# Generated by Django 5.1.3 on 2024-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_alter_member_birthday_alter_member_nicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nicName',
            field=models.CharField(max_length=100),
        ),
    ]
