# Generated by Django 5.1.3 on 2024-12-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginpage', '0002_alter_member_birthday_alter_member_nicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryBoard',
            fields=[
                ('dno', models.AutoField(primary_key=True, serialize=False)),
                ('dtitle', models.CharField(max_length=1000)),
                ('dcontent', models.TextField()),
                ('dhit', models.IntegerField(default=0)),
                ('ddate', models.DateTimeField(auto_now=True)),
                ('dfile', models.ImageField(null=True, upload_to='diary')),
                ('like_members', models.ManyToManyField(default='', related_name='diary_like_member', to='loginpage.member')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
            ],
        ),
    ]
