# Generated by Django 5.1.3 on 2024-12-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryboard',
            name='dlock',
            field=models.IntegerField(default=0),
        ),
    ]
