# Generated by Django 5.1.3 on 2024-12-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryboard',
            name='like_members',
        ),
    ]
