# Generated by Django 5.1.3 on 2024-12-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        ('loginpage', '0002_alter_member_birthday_alter_member_nicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('lno', models.AutoField(primary_key=True, serialize=False)),
                ('ltitle', models.CharField(max_length=1000)),
                ('lcontent', models.TextField()),
                ('ldate', models.DateTimeField(auto_now=True)),
                ('lhit', models.IntegerField(default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
            ],
        ),
    ]
