# Generated by Django 5.1.3 on 2024-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryboard_dlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryboard',
            name='diarytit',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
