# Generated by Django 5.1.3 on 2024-12-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_letter'),
        ('diary', '0002_remove_diaryboard_like_members'),
        ('diary', '0003_diaryboard_diarytit'),
    ]

    operations = [
    ]
