# Generated by Django 5.1.3 on 2024-12-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_groupdiary_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
