# Generated by Django 5.1.3 on 2024-12-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_merge_20241211_1657'),
        ('loginpage', '0002_alter_member_birthday_alter_member_nicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdiaryBoard',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('mtitle', models.CharField(max_length=1000)),
                ('mdate', models.DateField(null=True)),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
                ('nicName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic_names', to='loginpage.member')),
            ],
        ),
        migrations.DeleteModel(
            name='DiaryBoard',
        ),
    ]
