# Generated by Django 5.1.3 on 2024-12-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_delete_groupdiary'),
        ('loginpage', '0002_alter_member_birthday_alter_member_nicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiary',
            fields=[
                ('gno', models.AutoField(primary_key=True, serialize=False)),
                ('gtitle', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
            ],
        ),
    ]
