# Generated by Django 5.1.3 on 2024-12-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiary',
            name='gName',
            field=models.CharField(default='우리가족', max_length=100),
        ),
    ]
