# Generated by Django 5.1.3 on 2024-12-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_mdiaryboard_delete_diaryboard'),
        ('diary', '0009_groupdiary_gname'),
    ]

    operations = [
    ]
