# Generated by Django 5.1.3 on 2024-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0002_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
