# Generated by Django 5.1.3 on 2024-12-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0008_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
