# Generated by Django 5.1.3 on 2024-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0009_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='장소가 없습니다.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='memo',
            field=models.TextField(default='내용이없습니다.'),
        ),
    ]
