# Generated by Django 5.1.3 on 2024-12-16 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gno', models.IntegerField(default=0)),
                ('gtitle', models.CharField(max_length=200)),
                ('gName', models.CharField(default='우리 가족', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.IntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('ctitle', models.CharField(max_length=1000)),
                ('ccontent', models.TextField(null=True)),
                ('cdate', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary_images/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
                ('group_diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.groupdiary')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('lno', models.AutoField(primary_key=True, serialize=False)),
                ('ltitle', models.CharField(max_length=1000)),
                ('lcontent', models.TextField()),
                ('ldate', models.DateTimeField(auto_now=True)),
                ('lhit', models.IntegerField(default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
            ],
        ),
        migrations.CreateModel(
            name='MdiaryBoard',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('mtitle', models.CharField(max_length=1000)),
                ('mdate', models.DateField(null=True)),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
            ],
        ),
    ]
