# Generated by Django 5.1.3 on 2024-12-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_mdiaryboard_mdate_alter_mdiaryboard_mtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mdiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.mdiaryboard'),
        ),
    ]
