# Generated by Django 5.1.3 on 2024-12-23 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_content_group_diary_content_group_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
