# Generated by Django 5.1.3 on 2024-11-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='board',
            name='bgroup',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='bhit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='bindent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='bstep',
            field=models.IntegerField(default=0),
        ),
    ]
