# Generated by Django 5.1.3 on 2024-11-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_bdate_board_bgroup_board_bhit_board_bindent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bfile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
