# Generated by Django 5.1.3 on 2024-12-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nicName', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=10)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
