# Generated by Django 5.1.3 on 2024-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='nicName',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
