# Generated by Django 5.1.3 on 2024-12-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_member_created_group_member_joined_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(max_length=100),
        ),
    ]
