# Generated by Django 5.1.3 on 2024-12-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='role',
            field=models.IntegerField(),
        ),
    ]
