# Generated by Django 5.1.3 on 2024-12-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_alter_administrator_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='ano',
            field=models.IntegerField(default=0),
        ),
    ]
