# Generated by Django 5.1.3 on 2024-12-16 11:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginpage', '0002_member_created_group_member_joined_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaryNo', models.IntegerField(default=0)),
                ('diarydate', models.DateField(default=datetime.date.today)),
                ('emotionscore', models.IntegerField(default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member')),
            ],
        ),
    ]
