# Generated by Django 5.1.3 on 2024-12-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='diary.groupdiary'),
        ),
        migrations.AddField(
            model_name='member',
            name='joined_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='diary.groupdiary'),
        ),
    ]
