# Generated by Django 5.1.3 on 2024-12-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin1', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=1000)),
                ('bcontent', models.TextField()),
                ('bdate', models.DateTimeField(auto_now=True)),
                ('bfile', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('bfile_thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('userid', models.CharField(blank=True, max_length=100, null=True)),
                ('bmail', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin1.administrator')),
            ],
        ),
    ]
