# Generated by Django 5.1.3 on 2024-12-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginpage', '0002_member_created_group_member_joined_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(default='#0000FF', max_length=100)),
                ('title', models.CharField(default='제목이없습니다.', max_length=255, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('location', models.CharField(default='장소가 없습니다.', max_length=255)),
                ('repeat', models.CharField(choices=[('none', '없음'), ('daily', '매일'), ('weekly', '매주'), ('monthly', '매월'), ('yearly', '매년')], default='none', max_length=20)),
                ('memo', models.TextField(default='내용이없습니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginpage.member')),
            ],
        ),
    ]
